Empirical Discrepancy is defined as

$$ \widehat{\text{disc}_H}(q) = \sup\limits_{h\in H, h\in H_A} \left| \sum\limits^T_{t=1} q_t(L(h_t(X_{T+1}),h(X_{T+1})) - L(h_t,Z_t))\right|$$


How do we minimize the following?

$$ \widehat{\text{disc}_H}(q) + \sum\limits_{t=1}^T q_t L(h_t,Z_t)$$

First we need to modify an Online Expert

In [6]:
from Expert_Prediction.online_experts import *

In [7]:
import numpy as np

In [8]:
actual_values = np.random.randint(0,10,size=[40])
def create_expert(std,actual_values):
    return actual_values+np.random.randn(actual_values.size)*std
# Fixed Standard Deviations for each expert
stds = [1,0.1,0.03,0.5,1.3,2,5,1,2,5]
expert_predictions = np.array([create_expert(std,actual_values) for std in stds])

In [14]:
expert_predictions[:,:-1].shape

(10, 39)

In [13]:
actual_values[:-1].shape

(39,)

In [10]:
test1 = OnlineHedgeDoubling(n=10,T=50,loss_func=se)

In [185]:
hypotheses = []
for i in range(39):
    a = np.zeros(10)
    a[np.random.choice(10)]=1
    hypotheses.append(a)

In [186]:
hypotheses = np.array(hypotheses).T

In [106]:
predictions = (hypotheses * expert_predictions[:,:-1])

In [113]:
hypotheses_series = predictions.sum(axis=0)

In [120]:
losses_t = se(hypotheses_series,actual_values[:-1])

In [125]:
losses_t

array([2.81251379e-01, 1.20836531e+01, 4.36578044e-01, 1.36092227e+00,
       3.53949075e+00, 9.97113078e+00, 1.28150505e+02, 1.62655842e+00,
       3.36073960e-01, 1.29306976e-02, 1.03677406e+00, 7.63282041e-01,
       2.14001279e+01, 1.66293267e+01, 6.20483994e-01, 2.69278353e-03,
       1.93613123e+00, 4.78688794e-01, 1.52703935e+00, 1.21336277e+00,
       9.43265162e-01, 3.67192802e+01, 5.60682381e+00, 1.13385053e+01,
       3.59226683e-03, 1.94610806e-01, 1.36575447e-01, 1.16087696e+00,
       4.18650611e-01, 4.10015350e-01, 1.54579732e-01, 2.12265955e-03,
       6.90779570e+00, 2.77437082e-01, 1.15152514e+00, 2.23949399e-01,
       1.31543575e-03, 2.10536959e-01, 1.15850058e+00])

In [124]:
np.random.randn(39)*losses_t

array([ 4.61859433e-01, -1.15349826e+01,  5.61575462e-02,  3.01468696e-01,
       -1.10267932e+00,  7.40396795e+00,  3.96144990e+01,  5.58807517e-01,
       -1.87323489e-01,  9.68973434e-03, -8.01354485e-02, -8.58112971e-01,
       -2.28566266e+01,  8.51067644e-01, -4.96424044e-01,  2.29544943e-03,
        3.30612320e+00,  6.58633259e-01,  1.15036769e+00, -7.35917821e-01,
       -1.82843996e+00,  1.49154597e+01,  6.33779120e+00, -4.22985507e+00,
       -3.67847064e-03,  1.41975556e-01, -3.65325392e-01, -1.03106210e+00,
       -2.43652105e-02, -2.24922708e-01, -1.35945595e-01, -2.78210750e-03,
       -7.41513745e+00,  5.29539598e-01,  2.13815066e+00, -4.99773243e-01,
       -2.02135654e-05,  2.10148193e-01, -2.99380119e-01])

In [149]:
losses_t

array([2.81251379e-01, 1.20836531e+01, 4.36578044e-01, 1.36092227e+00,
       3.53949075e+00, 9.97113078e+00, 1.28150505e+02, 1.62655842e+00,
       3.36073960e-01, 1.29306976e-02, 1.03677406e+00, 7.63282041e-01,
       2.14001279e+01, 1.66293267e+01, 6.20483994e-01, 2.69278353e-03,
       1.93613123e+00, 4.78688794e-01, 1.52703935e+00, 1.21336277e+00,
       9.43265162e-01, 3.67192802e+01, 5.60682381e+00, 1.13385053e+01,
       3.59226683e-03, 1.94610806e-01, 1.36575447e-01, 1.16087696e+00,
       4.18650611e-01, 4.10015350e-01, 1.54579732e-01, 2.12265955e-03,
       6.90779570e+00, 2.77437082e-01, 1.15152514e+00, 2.23949399e-01,
       1.31543575e-03, 2.10536959e-01, 1.15850058e+00])

In [150]:
expert_predictions[:,39]

array([4.53153951, 3.97399212, 4.01611593, 3.7608536 , 5.19541397,
       3.74821712, 4.58448697, 5.69678644, 4.65131307, 4.21289229])

In [143]:
possible

NameError: name 'possible' is not defined

In [172]:
set_of_losses = np.array([se(np.dot(expert_predictions[:,39],hypotheses),h) for h in expert_predictions[:,39]])

In [175]:
set_of_losses.shape

(10, 39)

In [163]:
np.outer(np.random.randn(39),np.ones(10))

(39, 10)

In [181]:
np.dot(set_of_losses,np.random.randn(39)).shape

(10,)

In [180]:
np.dot(se(hypotheses_series,actual_values[:39]),np.random.randn(39))

-191.0257301185086

In [196]:
def discrepancy(q, hypotheses, updated_expert_predictions, expert_predictions, actual_values, loss_func=None):
    predictions = (hypotheses * expert_predictions)
    hypotheses_series = predictions.sum(axis=0)
    
    losses_t = loss_func(hypotheses_series,actual_values)
    
    q_weighted_losses_t = np.dot(losses_t,q)
    set_of_hypothesis_losses = np.array([loss_func(np.dot(updated_expert_predictions,hypotheses),h) for h in updated_expert_predictions])
    
    abs_total_losses = abs(np.dot(set_of_hypothesis_losses,q)-q_weighted_losses_t)
    sup_abs_total_losses = np.max(abs_total_losses)
    return sup_abs_total_losses

In [197]:
discrepancy(np.ones(39)/39,hypotheses,expert_predictions[:,39],expert_predictions[:,:39],actual_values[:39],loss_func=se)

2.1939857104728095